function [fitresult, gof] = fitbat(x_5C, y_5C)
%CREATEFIT(X_5C,Y_5C)
%  Create a fit.
%
%  Data for '5C' fit:
%      X Input: x_5C
%      Y Output: y_5C
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Jun-2024 15:23:01


%% Fit: '5C'.
[xData, yData] = prepareCurveData( x_5C, y_5C );

% Set up fittype and options.
ft = fittype( 'V0*(1-x*B)/(1-beta*x*B)-A', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'domain',[0.2 1]);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0.75 3 0];
opts.StartPoint = [0 0.75 3 0];
opts.Upper = [1 1 4 1];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'battery' );
% h = plot( fitresult, xData, yData, excludedPoints );
% legend( h, 'data', 'excluded', 'model', 'Location', 'SouthWest', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'x', 'Interpreter', 'none' );
% ylabel( 'y', 'Interpreter', 'none' );
% grid on


