function data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATADISCHARGE0C5 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DATADISCHARGE0C5 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  datadischarge0C5 = importfile("C:\Users\alex8\OneDrive - Università degli Studi di Parma\Desktop\batteries\new\data_discharge_0C5.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Jun-2024 14:51:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["q", "v"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["q", "v"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["q", "v"], "ThousandsSeparator", ".");

% Import the data
data = readtable(filename, opts);

end